# Generated by Django 3.1.4 on 2020-12-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tell_num', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('baz_type', models.CharField(max_length=50)),
                ('baz_num', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
