# Generated by Django 3.1.4 on 2020-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='baz_num',
            field=models.IntegerField(max_length=50),
        ),
    ]
