# Generated by Django 3.1.4 on 2020-12-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20201227_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='baz_num',
            field=models.IntegerField(),
        ),
    ]
