# Generated by Django 3.1.4 on 2020-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20201227_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tell_num',
            field=models.IntegerField(),
        ),
    ]
