# Generated by Django 3.1.4 on 2020-12-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20201228_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='baz_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
