# Generated by Django 3.1.4 on 2020-12-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20201228_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='baz_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
