# Generated by Django 3.1.4 on 2020-12-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20201229_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='baz_type',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
